- name: deploy LAMP stack
  hosts: test
  tasks:
    -  ansible.builtin.file:
         path: /tmp/test/
         state: directory
         mode: '0755'
    -  copy:
         src: ./
         dest: /tmp/test/
    -  community.docker.docker_compose:
         project_src: /tmp/test/
         files:
         - docker-compose.yml
